server:
   port: 9300
spring:
   application:
      name: medtech-service
eureka:
   client:
      serviceUrl:
         defaultZone: http://172.16.19.47:8761/eureka/

      
message:
  not_found: Khong tim thay .Vui long kiem tra lai
